#!/usr/bin/env python3
import datetime

def appendDate():
    month = int(input("Enter a month:\n"))
    day = int(input("Enter a day:\n"))
    actualDate = datetime.date(datetime.datetime.now().year, month, day)
    name = str(input("Enter the name of the event: "))
    birthdayDates = open("Events.txt", "a")
    birthdayDates.write(f"{actualDate}: {name}\n")

count = int(input("How many entries?:\n"))
for i in range(count):
    appendDate()

